spring:
  output:
    ansi:
      enabled: always

  jpa:
    open-in-view: false
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        generate_statistics: true
        ejb:
          naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        format_sql: true
        order_updates: true
        order_inserts: true
        jdbc:
          batch_size: 30
          batch_versioned_data: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: ["health", "info", "configprops", "env"]

logging:
  exception-conversion-word: "%msg%n%ex{full, sun, java, org}"
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG